Description:
  This template is built and deployed by the infrastructure pipeline in various stages (staging/production) as required.
  It specifies the resources that need to be created, like the SageMaker Endpoint. It can be extended to include resources like
  AutoScalingPolicy, API Gateway, etc,. as required.
Parameters:
  SageMakerProjectName:
    Type: String
    Description: Name of the project
    MinLength: 1
    MaxLength: 32
    AllowedPattern: ^[a-zA-Z](-*[a-zA-Z0-9])*
  ModelExecutionRoleArn:
    Type: String
    Description: Execution role used for deploying the model.
  StageName:
    Type: String
    Description:
      The name for a project pipeline stage, such as Staging or Prod, for
      which resources are provisioned and deployed.
  EndpointInstanceCount:
    Type: Number
    Description: Number of instances to launch for the endpoint.
    MinValue: 1
  EndpointInstanceType:
    Type: String
    Description: The ML compute instance type for the endpoint.
  S3PathToModels:
    Type: String
    Description: The S3 path where the models are stored. Needs to finish with forward slash (/).
    AllowedPattern: ^s3:\/\/[a-zA-Z0-9\-\/\.]*\/
  ContainerImageInference:
    Type: String
    Description: The ECR path where inference code is stored.
    AllowedPattern: ^[\S]+

Resources:
  Model:
    Type: AWS::SageMaker::Model
    Properties:
      PrimaryContainer:
        Mode: MultiModel
        ModelDataUrl: !Ref S3PathToModels
        Image: !Ref ContainerImageInference
      ExecutionRoleArn: !Ref ModelExecutionRoleArn

  EndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialInstanceCount: !Ref EndpointInstanceCount
          InitialVariantWeight: 1.0
          InstanceType: !Ref EndpointInstanceType
          ModelName: !GetAtt Model.ModelName
          VariantName: AllTraffic

  Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Sub ${SageMakerProjectName}-${StageName}
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
